name: meteo
description: Simple numeric weather application.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^3.0.0
  flutter_bloc: ^3.1.0
  equatable: ^1.0.2
  http: ^0.12.0
  meta: ^1.1.6
  intl: ^0.16.0
  diacritic: ^0.1.1
  sqflite: ^1.2.0
  path: ^1.6.4
  photo_view: ^0.9.1
  rxdart: ^0.23.1
  geolocator: ^5.2.0
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
